version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: starwars-postgres
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: starwars-redis
    restart: always
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: starwars-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  n8n:
    image: n8nio/n8n
    container_name: starwars-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=starwars-postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - REDIS_HOST=starwars-redis
      - REDIS_PORT=6379
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
    volumes:
      - ./n8n:/home/node/.n8n
    depends_on:
      - postgres
      - redis

  mongodb:
    image: mongo:7.0
    container_name: starwars-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: minhaSenhaSegura
    volumes:
      - ./mongo-data:/data/db

volumes:
  postgres_data:
  ollama_data:

